### ISSUE TITLE
Consider dropping Python 3.9 support

### ISSUE THREAD

**Issue by ucapbba** [heracles-ec/heracles#197]
According to [SPEC0](https://scientific-python.org/specs/spec-0000) it currently recommends dropping everything below 3.10, [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html) agrees similarly. Can read more about [the motivation here](https://scientific-python.org/specs/spec-0000/#motivation).

**Comment by ntessore** [comment]
The Euclid pipeline runs on Python 3.9, so this would cause a bit of a headache.
